methods are added to controller for crud and additional methods, dele…
wolox-training/kc-java pull request #9
Opened 2021-06-18 00:00 UTC by krcg93

## Summary
- methods are added to controller for crud and additional methods, delete method is added to model, user exceptions are added
## Trello Card
https://trello.com/c/u9l0nUuI/21-crear-user-controller-con-las-operaciones-crud-de-user

2021-06-18 19:49 UTC, JaimLus reviewed
Excellent job!

2021-06-18 19:49 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +        return userRepository.findByUsername(username);
What happens if not find it?

2021-06-18 19:49 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +            throws UserNotFoundException {
I think you don't need to have a throw exception.
The exception should extend from RuntimeException.

2021-06-18 19:49 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +            throws UserNotFoundException {
Check the throw.

2021-06-25 14:08 UTC, juandbc requested changes

2021-06-25 14:08 UTC, juandbc commented on src/main/java/wolox/training/controllers/UserController.java
> +    @DeleteMapping("/{id}")
Here it should response with 204

2021-06-25 14:08 UTC, juandbc commented on src/main/java/wolox/training/controllers/UserController.java
> +    public User updateUser(@RequestBody User user, @PathVariable Long id) {
Here it should response with 204

2021-06-25 14:08 UTC, juandbc commented on src/main/java/wolox/training/controllers/UserController.java
> +            throws UserNotFoundException {
It is not necessary the throws statement
```suggestion
    public User addBook(@PathVariable Long id, @RequestBody Book book) {
```

2021-06-25 14:08 UTC, juandbc commented on src/main/java/wolox/training/controllers/UserController.java
> +        return userRepository.save(user);
Good job throwing the exception when the user doesn't exist. But what happen when the book that you try to add is already added? It throws the exception but is missing the HTTP Status

2023-02-10 12:50 UTC, closed without merging